CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(1000),
    requestor_id INT REFERENCES users (id),
    created      TIMESTAMP,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(1000)                           NOT NULL,
    is_available BOOLEAN,
    owner_id     INT REFERENCES users (id),
    request_id   INT REFERENCES requests (id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP,
    end_date   TIMESTAMP,
    item_id    INT REFERENCES items (id)               NOT NULL,
    booker_id  INT REFERENCES users (id)               NOT NULL,
    status     VARCHAR(15),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(2000),
    item_id   INT REFERENCES items (id),
    author_id INT REFERENCES users (id),
    CONSTRAINT pk_comment PRIMARY KEY (id)
);
